include:
  - board: seeeduino_xiao_ble
    shield: totem_left
    snippet: zmk-usb-logging
  - board: seeeduino_xiao_ble
    shield: totem_right
    snippet: zmk-usb-logging
  - board: seeeduino_xiao_ble
    shield: totem_trackball
    snippet: zmk-usb-logging
  - board: seeeduino_xiao_ble
    shield: settings_reset
  - board: seeeduino_xiao_ble
    shield: totem_dongle dongle_screen
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: dongle-screen
